routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('categories.index');
});


Route::post('/categories/update-sort-category', 'CategoryController@updateSortCategory')->name('categories.updateSortCategory');
Route::resource('products', 'ProductController');
Route::get('/products/list/{category}', 'ProductController@index')->name('products.index');
Route::resource('categories', 'CategoryController');

app/Models/Category.php
<?php

namespace App\Models;

use App\Traits\InsertOnDuplicateKey;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{

    use InsertOnDuplicateKey;

    /**
     * @var string
     */
    protected $table = 'categories';

    /**
     * @var bool
     */
    public $timestamps = true;

    /**
     * @var array
     */
    protected $fillable = ['parent_id', 'name', 'sort_category'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function children()
    {
        return $this->hasMany(Category::class, 'parent_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function parent()
    {
        return $this->belongsTo(Category::class, 'parent_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function products()
    {
        return $this->hasMany(Product::class);
    }

    /**
     * Scope for sort by params.
     *
     * @param $query
     * @param  array  $sort
     *
     * @return mixed
     */
    public function scopeOfSort($query, array $sort)
    {
        foreach ($sort as $column => $direction) {
            $query->orderBy($column, $direction);
        }

        return $query;
    }

    /**
     * Make categories tree from collection.
     *
     * @param  \Illuminate\Database\Eloquent\Collection  $categories
     *
     * @return \Illuminate\Database\Eloquent\Collection
     */
    public static function makeTree(Collection $categories)
    {
        $grouped = $categories->groupBy('parent_id');

        foreach ($categories as $category) {
            if ($grouped->has($category->id)) {
                $category->children = $grouped[$category->id];
            }
        }

        return $categories->where('parent_id', 0);
    }

}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CategoryRequest;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $categories = $this->categoryService->getCategoriesTree();
        return view('categories.index', compact('categories'));
    }

    /**
     * Show form for create.
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        $categories = $this->categoryService->getCategoriesTree();
        $level = 0;
        return view('categories.create', compact('categories', 'level'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\CategoryRequest  $request
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(CategoryRequest $request)
    {
        $params = $request->all();
        $this->categoryService->saveCategory($params);
        return redirect()->route('categories.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     *
     * @return \Illuminate\View\View
     */
    public function edit($id)
    {
        $categories = $this->categoryService->getSortedCategories();
        $category = $this->categoryService->findCategory($categories, $id);
        $categories = Category::makeTree($categories);
        $level = 0;
        return view('categories.edit', compact('categories', 'level', 'category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\CategoryRequest  $request
     * @param  \App\Models\Category  $category
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(CategoryRequest $request, Category $category)
    {
        $params = $request->all();
        $this->categoryService->updateCategory($params, $category);
        return redirect()->route('categories.index');
    }

    /**
     * Update sort category.
     *
     * @param  \Illuminate\Http\Request  $request
     */
    public function updateSortCategory(Request $request)
    {
        $params = $request->all()['data'];
        $this->categoryService->updateOrder($params);
    }

}

resources/views/categories/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="site-section">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 col-md-10 col-lg-5">
                    <div><h2 class="text-black mb-4 mt-3">Add new category</h2></div>
                    <div>
                        <form action="{{ route('categories.store') }}" class="text-left" method="post">
                            @csrf

                            <div class="form-group">
                                <label for="name">Name <small class="text-danger">*</small></label>
                                <input type="text" name="name" class="form-control @error('name') is-invalid @enderror"
                                       id="name"
                                       min="3"
                                       max="255"
                                       value="{{ old('name') }}" required autofocus>
                                @include('layouts.input-error', ['field' => 'name'])
                            </div>

                            <div class="form-group">
                                <label for="parent_id">Parent category <small class="text-danger">*</small></label>
                                <select name="parent_id" id="parent_id" class="form-control @error('parent_id') is-invalid @enderror" required>
                                    <option value="0" selected>Main</option>
                                    @foreach($categories as $category)
                                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                                        @if($category->children->first())
                                            @include('categories.partials.child-option', ['childrenCategories' => $category->children, 'level' => $level + 1])
                                        @endif
                                    @endforeach
                                </select>
                                @include('layouts.input-error', ['field' => 'parent_id'])
                            </div>

                            <div class="mb-4">
                                <button type="submit" class="btn btn-md btn-primary mr-2">Add</button>
                                <a href="{{ route('categories.index') }}" class="btn btn-md btn-secondary">Cancel</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/categories/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="site-section">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 col-md-10 col-lg-5">
                    <div><h2 class="text-black mb-4 mt-3">Add new category</h2></div>
                    <div>
                        <form action="{{ route('categories.update', $category->id) }}" class="text-left" method="post">
                            @csrf
                            @method('put')

                            <div class="form-group">
                                <label for="name">Name <small class="text-danger">*</small></label>
                                <input type="text" name="name" class="form-control @error('name') is-invalid @enderror"
                                       id="name"
                                       min="3"
                                       max="255"
                                       value="{{ old('name', isset($category) ? $category->name : null) }}" required autofocus>
                                @include('layouts.input-error', ['field' => 'name'])
                            </div>

                            <div class="form-group">
                                <label for="parent_id">Parent category <small class="text-danger">*</small></label>
                                <select name="parent_id" id="parent_id" class="form-control @error('parent_id') is-invalid @enderror" required>
                                    @if($category->parent)
                                        <option value="{{ $category->parent->id }}" selected>{{ $category->parent->name }}</option>
                                    @else
                                        <option value="0" selected>Main</option>
                                    @endif
                                    @foreach($categories as $category)
                                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                                        @if($category->children->first())
                                            @include('categories.partials.child-option', ['childrenCategories' => $category->children, 'level' => $level + 1])
                                        @endif
                                    @endforeach
                                </select>
                                @include('layouts.input-error', ['field' => 'parent_id'])
                            </div>

                            <div class="mb-4">
                                <button type="submit" class="btn btn-md btn-primary mr-2">Update</button>
                                <a href="{{ route('categories.index') }}" class="btn btn-md btn-secondary">Cancel</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/categories/index.blade.php
@extends('layouts.app')

@section('content')
    <h1 class="mt-3 mb-3">Categories</h1>
    @include('categories.partials.tree')
    <a href="{{ route('categories.create') }}" class="btn btn-md btn-secondary mt-4">Add category</a>
@endsection