routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('categories.index');
});


Route::post('/categories/update-sort-category', 'CategoryController@updateSortCategory')->name('categories.updateSortCategory');
Route::resource('products', 'ProductController');
Route::get('/products/list/{category}', 'ProductController@index')->name('products.index');
Route::resource('categories', 'CategoryController');

app/Models/Product.php
<?php

namespace App\Models;

use App\Traits\InsertOnDuplicateKey;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{

    use InsertOnDuplicateKey;

    /**
     * @var string
     */
    protected $table = 'products';

    /**
     * @var bool
     */
    public $timestamps = true;

    /**
     * @var array
     */
    protected $fillable = ['category_id', 'name', 'price'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function category()
    {
        return $this->belongsTo(Category::class);
    }

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProductRequest;
use App\Models\Product;
use App\Models\Category;

class ProductController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @param  \App\Models\Category  $category
     *
     * @return \Illuminate\View\View
     */
    public function index(Category $category)
    {
        $products = Product::whereCategory_id($category->id)->get();
        return view('products.index', compact('products', 'category'));
    }

    /**
     * Show form for create.
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        $categories = $this->categoryService->getCategoriesTree();
        $level = 0;
        return view('products.create', compact('categories', 'level'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\ProductRequest  $request
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(ProductRequest $request)
    {
        $params = $request->all();
        Category::findOrFail($params['category_id']);
        Product::create($params);
        return redirect()->route('categories.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     *
     * @return \Illuminate\View\View
     */
    public function edit($id)
    {
        $product = Product::with('category')->findOrFail($id);
        $categories = $this->categoryService->getCategoriesTree();
        $level = 0;
        return view('products.edit', compact('categories', 'level', 'product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\ProductRequest  $request
     * @param  \App\Models\Product  $product
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(ProductRequest $request, Product $product)
    {
        $params = $request->all();
        $product->update($params);
        return redirect()->route('categories.index');
    }

}

resources/views/products/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="site-section">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 col-md-10 col-lg-5">
                    <div><h2 class="text-black mb-4 mt-3">Add new product</h2></div>
                    <div>
                        <form action="{{ route('products.store') }}" class="text-left" method="post">
                            @csrf

                            <div class="form-group">
                                <label for="name">Name <small class="text-danger">*</small></label>
                                <input type="text" name="name" class="form-control @error('name') is-invalid @enderror"
                                       id="name"
                                       min="3"
                                       max="255"
                                       value="{{ old('name') }}" required autofocus>
                                @include('layouts.input-error', ['field' => 'name'])
                            </div>

                            <div class="form-group">
                                <label for="price">Price <small class="text-danger">*</small></label>
                                <input type="number" name="price" class="form-control @error('price') is-invalid @enderror"
                                       id="price"
                                       min="0"
                                       value="{{ old('price') }}" required autofocus>
                                @include('layouts.input-error', ['field' => 'price'])
                            </div>

                            <div class="form-group">
                                <label for="parent_id">Category <small class="text-danger">*</small></label>
                                <select name="category_id" id="category_id" class="form-control @error('category_id') is-invalid @enderror" required>
                                    @foreach($categories as $category)
                                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                                        @if($category->children->first())
                                            @include('categories.partials.child-option', ['childrenCategories' => $category->children, 'level' => $level + 1])
                                        @endif
                                    @endforeach
                                </select>
                                @include('layouts.input-error', ['field' => 'category_id'])
                            </div>

                            <div class="mb-4">
                                <button type="submit" class="btn btn-md btn-primary mr-2">Add</button>
                                <a href="{{ route('categories.index') }}" class="btn btn-md btn-secondary">Cancel</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/products/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="site-section">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 col-md-10 col-lg-5">
                    <div><h2 class="text-black mb-4 mt-3">Add new product</h2></div>
                    <div>
                        <form action="{{ route('products.update', $product) }}" class="text-left" method="post">
                            @csrf
                            @method('put')

                            <div class="form-group">
                                <label for="name">Name <small class="text-danger">*</small></label>
                                <input type="text" name="name" class="form-control @error('name') is-invalid @enderror"
                                       id="name"
                                       min="3"
                                       max="255"
                                       value="{{ old('name', isset($product) ? $product->name : null) }}" required autofocus>
                                @include('layouts.input-error', ['field' => 'name'])
                            </div>

                            <div class="form-group">
                                <label for="price">Price <small class="text-danger">*</small></label>
                                <input type="number" name="price" class="form-control @error('price') is-invalid @enderror"
                                       id="price"
                                       min="0"
                                       value="{{ old('price', isset($product) ? $product->price : null) }}" required autofocus>
                                @include('layouts.input-error', ['field' => 'price'])
                            </div>

                            <div class="form-group">
                                <label for="parent_id">Category <small class="text-danger">*</small></label>
                                <select name="category_id" id="category_id" class="form-control @error('category_id') is-invalid @enderror" required>
                                    <option value="{{ $product->category->id }}" selected>{{ $product->category->name }}</option>
                                    @foreach($categories as $category)
                                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                                        @if($category->children->first())
                                            @include('categories.partials.child-option', ['childrenCategories' => $category->children, 'level' => $level + 1])
                                        @endif
                                    @endforeach
                                </select>
                                @include('layouts.input-error', ['field' => 'category_id'])
                            </div>

                            <div class="mb-4">
                                <button type="submit" class="btn btn-md btn-primary mr-2">Update</button>
                                <a href="{{ route('categories.index') }}" class="btn btn-md btn-secondary">Cancel</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/products/index.blade.php
@extends('layouts.app')

@section('content')
    <h1 class="mt-3 mb-3">{{ $category->name }}</h1>
    @include('products.partials.card')
    <a href="{{ route('products.create') }}" class="btn btn-md btn-secondary mt-4">Add product</a>
@endsection